### ISSUE TITLE
Diagram Wrong

### ISSUE THREAD

**Issue by barbBTC** [UpstreamData/UpstreamData.github.io#1]
In the [Winterization File](https://github.com/UpstreamData/UpstreamData.github.io/blob/main/guides/winterization/winterization_guide.pdf), the diagram shows the deflector pointing down for heat recirc but it should show the slider being adjusted and not the deflector being flipped.

**Comment by UpstreamData** [comment]
Actually, that diagram is for old style hashhuts, which use deflectors without sliders, so they must be flipped manually.
